export const config = {
  AZURE_CLIENT_ID: process.env.AZURE_CLIENT_ID!,
  AZURE_OBJECT_ID: process.env.AZURE_OBJECT_ID!,
  AZURE_TENANT_ID: process.env.AZURE_TENANT_ID!,
  AZURE_CLIENT_SECRET_ID: process.env.AZURE_CLIENT_SECRET_ID!,
  AZURE_CLIENT_SECRET_VALUE: process.env.AZURE_CLIENT_SECRET_VALUE!,
  REDIRECT_URI: process.env.REDIRECT_URI!,
  TRELLO_TOKEN: process.env.TRELLO_TOKEN!,
  TRELLO_API_KEY: process.env.TRELLO_API_KEY!,
  TRELLO_API_SECRET: process.env.TRELLO_API_SECRET!,
};
